<?xml version="1.0" ?>
<!--  This document gives the expected error messages for the testsuite -->

<!DOCTYPE results [
  <!ELEMENT test ANY>
  <!ATTLIST test
            ambiguous  CDATA "no"
            unsupported CDATA "no"
            id ID #REQUIRED >

  <!--  If ambiguous is set to yes, the test is ambiguous, ie its
        behavior seems to contradict other tests. Such tests are not
        run by default -->
  <!--  If unsupported is set to yes, then the test uses unsupported
        features by XML/Ada. The test should be supported to claim full
        compatibility, of course, but this is pending implementation. In
        this case, it is recommended that the node's contents explains what
        feature is unsupported.
        An unsupported test of type "invalid" is still run to check that XML/Ada
        correctly detects the well-formedness of the document -->
  <!--  id is the unique ID of the test -->

  <!ENTITY attribute_is_ncname
           "Attribute must contain Names with no colon: " >
  <!ENTITY invalid_notation_decl "Invalid notation declaration">
  <!ENTITY expect_space          "Expecting a space">

]>
<results>
  <!--  These tests are apparently wrong, given the Errata E14
        http://www.w3.org/XML/xml-V10-2e-errata -->
  <test id="ibm-invalid-P50-ibm50i01.xml"  ambiguous="yes" />
  <test id="ibm-not-wf-p28a-ibm28an01.xml" ambiguous="yes" />
  <test id="not-wf-not-sa-009"             ambiguous="yes" />
  <test id="not-wf-sa-074"                 ambiguous="yes" />
  <test id="not-wf-sa-104"                 ambiguous="yes" />
  <test id="not-wf-sa-182"                 ambiguous="yes" />

  <!--  To be implemented -->
  <test id="rmt-e2e-55" unsupported="yes" >
     Reference to unparsed entity in entity valie is an error, not forbidden
  </test>
  <test id="inv-not-sa14" unsupported="yes" />  <!--  CDATA as whitespace -->
  <test id="el04" unsupported="yes" />          <!--  duplicate element decl -->
  <!--  Needs to analyse the content model -->
  <test id="rmt-e2e-34" unsupported="yes" />
  <test id="rmt-e2e-2a" unsupported="yes" />
  <test id="ibm-invalid-P51-ibm51i03" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i02" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i01" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i03" unsupported="yes" />
  <test id="attr16" unsupported="yes" />  <!-- Default attribute value -->
  <test id="attr15" unsupported="yes" />  <!-- Default attribute value -->
  <test id="optional25" unsupported="yes" />  <!-- check content model -->
  <test id="optional24" unsupported="yes" />  <!-- check content model -->
  <test id="optional23" unsupported="yes" />  <!-- check content model -->
  <test id="optional22" unsupported="yes" />  <!-- check content model -->
  <test id="optional21" unsupported="yes" />  <!-- check content model -->
  <test id="optional20" unsupported="yes" />  <!-- check content model -->
  <test id="optional19" unsupported="yes" />  <!-- check content model -->
  <test id="optional18" unsupported="yes" />  <!-- check content model -->
  <test id="optional17" unsupported="yes" />  <!-- check content model -->
  <test id="optional16" unsupported="yes" />  <!-- check content model -->
  <test id="optional15" unsupported="yes" />  <!-- check content model -->
  <test id="optional14" unsupported="yes" />  <!-- check content model -->
  <test id="optional13" unsupported="yes" />  <!-- check content model -->
  <test id="optional12" unsupported="yes" />  <!-- check content model -->
  <test id="optional11" unsupported="yes" />  <!-- check content model -->
  <test id="optional10" unsupported="yes" />  <!-- check content model -->
  <test id="optional09" unsupported="yes" />  <!-- check content model -->
  <test id="optional08" unsupported="yes" />  <!-- check content model -->
  <test id="optional07" unsupported="yes" />  <!-- check content model -->
  <test id="optional06" unsupported="yes" />  <!-- check content model -->
  <test id="optional05" unsupported="yes" />  <!-- check content model -->
  <test id="optional04" unsupported="yes" />  <!-- check content model -->
  <test id="optional03" unsupported="yes" />  <!-- check content model -->
  <test id="optional02" unsupported="yes" />  <!-- check content model -->
  <test id="optional01" unsupported="yes" />  <!-- check content model -->
  <test id="inv-dtd03"  unsupported="yes" />  <!-- check content model -->
  <test id="inv-dtd01"  unsupported="yes" />  <!-- duplicate in content model -->
  <test id="el03"       unsupported="yes" />  <!-- check content model -->
  <test id="el01"       unsupported="yes" />  <!-- check content model -->
  <test id="el05"       unsupported="yes" />  <!-- invalid content model -->
  <test id="el06"       unsupported="yes" />  <!-- empty element -->
  <test id="el02"       unsupported="yes" />  <!-- empty element -->
  <test id="ibm-invalid-P60-ibm60i03.xml" unsupported="yes" />
  <test id="ibm-invalid-P59-ibm59i01.xml" unsupported="yes" />
  <test id="ibm-invalid-P51-ibm51i03.xml" unsupported="yes" />
  <test id="ibm-invalid-P45-ibm45i01.xml" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i04.xml" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i03.xml" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i02.xml" unsupported="yes" />
  <test id="ibm-invalid-P39-ibm39i01.xml" unsupported="yes" />
  <test id="ibm-invalid-P32-ibm32i04.xml" unsupported="yes"/><!--standalone-->
  <test id="ibm-invalid-P32-ibm32i03.xml" unsupported="yes"/><!--standalone-->
  <test id="ibm-invalid-P32-ibm32i01.xml" unsupported="yes"/><!--standalone-->
  <test id="not-wf-sa-084" unsupported="yes"
    >084.xml:4:24: Undefined entity 'e'</test>  <!--  Incorrect error message -->

  <!--  The following tests require validation with DTD. The implementation
        should be shared with schemas -->
  <test id="rmt-e2e-15h" unsupported="yes" />
  <test id="rmt-e2e-15g" unsupported="yes" />
  <test id="rmt-e2e-15d" unsupported="yes" />
  <test id="rmt-e2e-15c" unsupported="yes" />
  <test id="rmt-e2e-15b" unsupported="yes" />
  <test id="rmt-e2e-15a" unsupported="yes" />
  <test id="ibm-invalid-P60-ibm60i03" unsupported="yes" />
  <test id="ibm-invalid-P59-ibm59i01" unsupported="yes" /> <!-- enums -->
  <test id="attr07"                       unsupported="yes" /> <!-- enums -->
  <test id="ibm-invalid-P56-ibm56i10" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i08" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i06" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i02" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i10.xml" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i08.xml" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i06.xml" unsupported="yes" /> <!-- ids -->
  <test id="ibm-invalid-P56-ibm56i02.xml" unsupported="yes" /> <!-- ids -->
  <test id="id09"                         unsupported="yes" /> <!-- ids and idref -->
  <test id="id08"                         unsupported="yes" /> <!-- ids and idref -->
  <test id="id03"                         unsupported="yes" /> <!-- one id per elem-->
  <test id="id02"                         unsupported="yes" /> <!-- ids unique -->
  <test id="ibm-invalid-P45-ibm45i01" unsupported="yes" /> <!-- <!ELEM -->
  <test id="ibm-invalid-P39-ibm39i04" unsupported="yes" /> <!-- <!ELEM -->
  <test id="ibm-invalid-P32-ibm32i04" unsupported="yes" /> <!-- standalone -->
  <test id="ibm-invalid-P32-ibm32i03" unsupported="yes" /> <!-- standalone -->
  <test id="ibm-invalid-P32-ibm32i01" unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa12"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa11"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa10"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa09"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa07"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa06"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa05"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa04"                 unsupported="yes" /> <!-- standalone -->
  <test id="inv-not-sa01"                 unsupported="yes" /> <!-- standalone -->
  <test id="empty" unsupported="yes" />       <!-- whitespace -->
  <test id="o-p75pass1" unsupported="yes" />  <!-- missing element decl -->
  <test id="o-p74pass1" unsupported="yes" />  <!-- missing element decl -->
  <test id="attr04"     unsupported="yes" />  <!-- notations must be declared -->
  <test id="attr03"     unsupported="yes" />  <!-- notations must be declared -->
  <test id="invalid-not-sa-022" unsupported="yes" /> <!--  conditional section -->

  <!--  Known error messages 
        This is the full list of error messages expected when running the testsuite
    -->

  <test id="id01"
     >id01.xml:5:6: &attribute_is_ncname;id</test>
  <test id="id06"
     >id06.xml:11:2: &attribute_is_ncname;idref</test>
  <test id="id07"
     >id07.xml:12:2: &attribute_is_ncname;idrefs</test>
  <test id="attr09"
     >attr09.xml:7:18: &attribute_is_ncname;value
attr09.xml:18:41: [VC] Attribute not declared in DTD: name
attr09.xml:18:6: &attribute_is_ncname;value</test>
  <test id="attr10"
     >attr10.xml:7:19: &attribute_is_ncname;value
attr10.xml:18:41: [VC] Attribute not declared in DTD: name
attr10.xml:18:6: &attribute_is_ncname;value</test>
  <test id="o-p06fail1"
     >p06fail1.xml:12:2: &attribute_is_ncname;refs</test>
  <test id="ibm-invalid-P56-ibm56i01"
     >ibm56i01.xml:8:2: &attribute_is_ncname;UniqueName</test>
  <test id="ibm-invalid-P56-ibm56i07"
     >ibm56i07.xml:13:2: &attribute_is_ncname;reference</test>
  <test id="ibm-invalid-P56-ibm56i09"
     >ibm56i09.xml:16:2: &attribute_is_ncname;reference</test>
  <test id="rmt-ns10-045"
     >045.xml:7:2: &attribute_is_ncname;id</test>
  <test id="rmt-ns10-046"
     >046.xml:8:2: &attribute_is_ncname;ref
046.xml:9:3: &attribute_is_ncname;id</test>
       
  <test id="ibm-not-wf-P82-ibm82n03"
     >ibm82n03.xml:7:23: &invalid_notation_decl;</test>
  <test id="ibm-not-wf-P83-ibm83n01"
     >ibm83n01.xml:7:28: &invalid_notation_decl;</test>
  <test id="ibm-not-wf-P83-ibm83n03"
     >ibm83n03.xml:7:23: &invalid_notation_decl;</test>
  <test id="ibm-not-wf-P83-ibm83n06"
     >ibm83n06.xml:7:23: &invalid_notation_decl;</test>
  <test id="rmt-ns10-044"
     >044.xml:5:15: &invalid_notation_decl;</test>

  <test id="not-wf-sa-045"
     >045.xml:2:3: &expect_space;</test> 
  <test id="not-wf-sa-046"
     >046.xml:2:3: &expect_space;</test>
  <test id="not-wf-sa-062"
     >062.xml:2:13: &expect_space;</test>
  <test id="not-wf-sa-064"
     >064.xml:3:21: &expect_space;</test>
  <test id="not-wf-sa-065"
     >065.xml:3:17: &expect_space;</test>
  <test id="not-wf-sa-066"
     >066.xml:3:27: &expect_space;</test>
  <test id="not-wf-sa-067"
     >067.xml:3:23: &expect_space;</test>
  <test id="not-wf-sa-137"
     >137.xml:2:14: &expect_space;</test>
  <test id="not-wf-sa-141"
     >entity e:1:3: &expect_space;</test>
  <test id="not-wf-sa-165"
     >165.xml:2:9: &expect_space;</test>
  <test id="not-wf-sa-186"
     >186.xml:5:9: &expect_space;</test>
  <test id="attlist10"
     >attlist10.xml:6:20: &expect_space;</test>
  <test id="attlist11"
     >attlist11.xml:6:20: &expect_space;</test>
  <test id="o-p04fail1"
     >p04fail1.xml:1:3: &expect_space;</test>
  <test id="o-p04fail2"
     >p04fail2.xml:1:3: &expect_space;</test>
  <test id="o-p04fail3"
     >p04fail3.xml:1:3: &expect_space;</test>
  <test id="o-p40fail1"
     >p40fail1.xml:1:15: &expect_space;</test>
  <test id="o-p42fail3"
     >p42fail3.xml:1:5: &expect_space;</test>
  <test id="o-p44fail2"
     >p44fail2.xml:1:5: &expect_space;</test>
  <test id="o-p44fail4"
     >p44fail4.xml:1:15: &expect_space;</test>
  <test id="o-p45fail2"
     >p45fail2.xml:3:14: &expect_space;</test>
  <test id="o-p53fail1"
     >p53fail1.xml:4:24: &expect_space;</test>
  <test id="o-p53fail2"
     >p53fail2.xml:4:18: &expect_space;</test>
  <test id="o-p53fail4"
     >p53fail4.xml:4:24: &expect_space;</test>
  <test id="o-p56fail1"
     >p56fail1.xml:4:21: &expect_space;</test>
  <test id="o-p56fail4"
     >p56fail4.xml:4:25: &expect_space;</test>
  <test id="o-p60fail2"
     >p60fail2.xml:4:31: &expect_space;</test>
  <test id="o-p60fail4"
     >p60fail4.xml:4:31: &expect_space;</test>
  <test id="o-p71fail1"
     >p71fail1.xml:4:12: &expect_space;</test>
  <test id="o-p71fail4"
     >p71fail4.xml:4:9: &expect_space;</test>
  <test id="o-p72fail1"
     >p72fail1.xml:4:9: &expect_space;</test>
  <test id="o-p72fail3"
     >p72fail3.xml:4:14: &expect_space;</test>
  <test id="o-p74fail2"
     >p74fail2.xml:4:14: &expect_space;</test>
  <test id="o-p75fail1"
     >p75fail1.xml:3:20: &expect_space;</test>
  <test id="o-p75fail2"
     >p75fail2.xml:3:20: &expect_space;</test>
  <test id="o-p76fail3"
     >p76fail3.xml:5:35: &expect_space;</test>
  <test id="ibm-not-wf-P10-ibm10n03"
     >ibm10n03.xml:14:22: &expect_space;</test>
  <test id="ibm-not-wf-P10-ibm10n07"
     >ibm10n07.xml:14:22: &expect_space;</test>
  <test id="ibm-not-wf-P40-ibm40n01"
     >ibm40n01.xml:7:7: &expect_space;</test>
  <test id="ibm-not-wf-P40-ibm40n02"
     >ibm40n02.xml:7:11: &expect_space;</test>
  <test id="ibm-not-wf-P40-ibm40n03"
     >ibm40n03.xml:7:7: &expect_space;</test>
  <test id="ibm-not-wf-P44-ibm44n02"
     >ibm44n02.xml:7:7: &expect_space;</test>
  <test id="ibm-not-wf-P44-ibm44n03"
     >ibm44n03.xml:7:18: &expect_space;</test>
  <test id="ibm-not-wf-P45-ibm45n02"
     >ibm45n02.xml:5:15: &expect_space;</test>
  <test id="ibm-not-wf-P45-ibm45n04"
     >ibm45n04.xml:5:15: &expect_space;</test>
  <test id="ibm-not-wf-P53-ibm53n02"
     >ibm53n02.xml:6:28: &expect_space;</test>
  <test id="ibm-not-wf-P53-ibm53n04"
     >ibm53n04.xml:6:18: &expect_space;</test>
  <test id="ibm-not-wf-P60-ibm60n05"
     >ibm60n05.xml:7:36: &expect_space;</test>
  <test id="ibm-not-wf-P71-ibm71n01"
     >ibm71n01.xml:6:9: &expect_space;</test>
  <test id="ibm-not-wf-P71-ibm71n02"
     >ibm71n02.xml:6:13: &expect_space;</test>
  <test id="ibm-not-wf-P71-ibm71n03"
     >ibm71n03.xml:6:13: &expect_space;</test>
  <test id="ibm-not-wf-P72-ibm72n01"
     >ibm72n01.xml:6:9: &expect_space;</test>
  <test id="rmt-ns10-043"
     >043.xml:5:11: &expect_space;</test>
  <test id="ibm-not-wf-P72-ibm72n03"
     >ibm72n03.xml:6:16: &expect_space;</test>
  <test id="ibm-not-wf-P72-ibm72n04"
     >ibm72n04.xml:6:16: &expect_space;</test>
  <test id="ibm-not-wf-P72-ibm72n09"
     >ibm72n09.xml:6:9: &expect_space;</test>
  <test id="ibm-not-wf-P75-ibm75n05"
     >ibm75n05.xml:6:23: &expect_space;</test>
  <test id="ibm-not-wf-P75-ibm75n09"
     >ibm75n09.xml:4:11: &expect_space;</test>
  <test id="ibm-not-wf-P76-ibm76n05"
     >ibm76n05.xml:8:41: &expect_space;</test>
  <test id="ibm-not-wf-P76-ibm76n06"
     >ibm76n06.xml:8:41: &expect_space;</test>
  <test id="ibm-not-wf-P83-ibm83n04"
     >ibm83n04.xml:7:28: &expect_space;</test>
  <test id="rmt-ns10-015"
     >015.xml:3:3: &expect_space;</test>
  <test id="rmt-ns10-043"
     >043.xml:5:11: &expect_space;</test>

  <test id="invalid--001"
    >entity %e:1:2: Entity values must be self-contained</test>
  <test id="invalid--002"
    >entity %e:1:2: Entity values must be self-contained</test>
  <test id="invalid--003"
    >003.ent:2:18: Entity values must be self-contained</test>
  <test id="invalid--004"
    >entity %e2:1:2: Entity values must be self-contained</test>
  <test id="invalid--005"
    >entity %e:1:2: Entity values must be self-contained</test>
  <test id="invalid--006"
    >entity %e:1:11: Entity values must be self-contained</test>
  <test id="not-wf-not-sa-005"
    >005.ent:2:1: Undefined entity '%e'</test>
  <test id="invalid--dtd06"
    >dtd06.xml:3:5: Undefined entity '%undefined'</test>
  <test id="not-wf-sa-001"
    >001.ent:1:1: Entity cannot reference itself</test>
  <test id="not-wf-sa-002"
    >002.ent:1:21: 'encoding' must be specified for &lt;?xml?&gt; in external entities</test>
  <test id="not-wf-not-sa-001"
    >001.ent:3:2: Conditional section must be properly terminated</test>
  <test id="not-wf-not-sa-002"
    >entity %e:1:2: &lt;?xml?&gt; instruction must be first in document</test>
  <test id="not-wf-not-sa-003"
    >003.ent:3:1: Conditional section must be properly terminated</test>
  <test id="not-wf-not-sa-004"
    >004.ent:3:1: Conditional section must be properly terminated</test>
  <test id="not-wf-not-sa-006"
    >006.ent:2:1: Conditional sections need '[' after INCLUDE or IGNORE</test>
  <test id="not-wf-not-sa-007"
    >007.ent:1:1: Element not allowed in the DTD</test>
  <test id="not-wf-not-sa-008"
    >008.ent:2:17: Entity references must end with ';'.
Did you want to use &amp;amp;?</test>
  <test id="not-wf-attlist01"
    >attlist01.xml:7:10: Invalid type for attribute</test>
  <test id="not-wf-attlist02"
    >attlist02.xml:7:10: Invalid type for attribute</test>
  <test id="not-wf-attlist03"
    >attlist03.xml:7:11: Invalid character ',' in ATTLIST enumeration</test>
  <test id="not-wf-attlist04"
    >attlist04.xml:7:10: Invalid type for attribute</test>
  <test id="not-wf-attlist05"
    >attlist05.xml:7:11: Invalid type for attribute</test>
  <test id="not-wf-attlist06"
    >attlist06.xml:7:10: Invalid type for attribute</test>
  <test id="not-wf-attlist07"
    >attlist07.xml:7:10: Invalid type for attribute</test>
  <test id="not-wf-attlist08"
    >attlist08.xml:7:18: Invalid default declaration for the attribute</test>
  <test id="not-wf-attlist09"
    >attlist09.xml:5:18: Invalid default declaration for the attribute</test>
  <test id="not-wf-attlist10"
    >attlist10.xml:6:20: Expecting a space</test>
  <test id="not-wf-attlist11"
    >attlist11.xml:6:20: Expecting a space</test>
  <test id="not-wf-cond01"
    >entity %MAYBE:3:1: Invalid declaration</test>
  <test id="not-wf-cond02"
    >cond.dtd:3:1: Invalid declaration</test>
  <test id="not-wf-content01"
    >content01.xml:3:20: Invalid location for '+', '?' or '*' operators</test>
  <test id="not-wf-content02"
    >content02.xml:3:20: Invalid location for '+', '?' or '*' operators</test>
  <test id="not-wf-content03"
    >content03.xml:3:20: Invalid location for '+', '?' or '*' operators</test>
  <test id="not-wf-decl01"
    >decl01.ent:1:38: Text declarations &lt;?xml?&gt; in external entity cannot specify parameters other than 'version' and 'encoding'</test>
  <test id="not-wf-dtd00"
    >dtd00.xml:2:31: Expecting operator in content model</test>
  <test id="not-wf-dtd01"
    >dtd01.xml:2:31: Cannot mix ',' and '|' in content model</test>
  <test id="not-wf-dtd02"
    >dtd02.xml:5:6: Entity references must end with ';'.
Did you want to use &amp;amp;?</test>
  <test id="not-wf-dtd03"
    >dtd03.xml:5:9: Entity references must end with ';'.
Did you want to use &amp;amp;?</test>
  <test id="not-wf-dtd04"
    >dtd04.xml:4:26: Expecting a string after PUBLIC</test>
  <test id="not-wf-dtd05"
    >dtd05.xml:4:34: Expecting a string after SYSTEM</test>
  <test id="not-wf-dtd07"
    >dtd07.dtd:1:20: 'encoding' must be specified for &lt;?xml?&gt; in external entities</test>
  <test id="not-wf-element00"
    >element00.xml:3:5: Tags must end with a '&gt;' symbol</test>
  <test id="not-wf-element01"
    >element01.xml:3:7: Tags must end with a '&gt;' symbol</test>
  <test id="not-wf-element02"
    >element02.xml:3:6: Invalid name: '%'</test>
  <test id="not-wf-element03"
    >element03.xml:3:6: Invalid name: '%'</test>
  <test id="not-wf-element04"
    >element04.xml:3:5: Invalid characters '&lt;!-' in stream</test>
  <test id="not-wf-encoding01"
    >encoding01.xml:1:31: Illegal character ' ' in encoding value</test>
  <test id="not-wf-encoding02"
    >encoding02.xml:1:31: Illegal character '/' in encoding value</test>
  <test id="not-wf-encoding03"
    >encoding03.xml:1:31: Illegal character ')' in encoding value</test>
  <test id="not-wf-encoding04"
    >encoding04.xml:1:31: Illegal character ':' in encoding value</test>
  <test id="not-wf-encoding05"
    >encoding05.xml:1:31: Illegal character '@' in encoding value</test>
  <test id="not-wf-encoding06"
    >encoding06.xml:1:31: Illegal character '+' in encoding value</test>
  <test id="not-wf-encoding07"
    >dtd07.dtd:1:20: 'encoding' must be specified for &lt;?xml?&gt; in external entities</test>
  <test id="not-wf-pi"
    >pi.xml:4:10: Must have space between target and data</test>
  <test id="not-wf-pubid05"
    >pubid05.xml:5:45: Expecting SystemID after PUBLIC</test>
  <test id="not-wf-sgml01"
    >sgml01.xml:8:0: Node &lt;root&gt; is not closed</test>
  <test id="not-wf-sgml02"
    >sgml02.xml:1:2: &lt;?xml?&gt; instruction must be first in document</test>
  <test id="not-wf-sgml03"
    >sgml03.xml:3:21: '--' cannot appear in comments</test>
  <test id="not-wf-sgml04"
    >sgml04.xml:7:15: Expecting a Name</test>
  <test id="not-wf-sgml05"
    >sgml05.xml:8:16: Expecting a Name</test>
  <test id="not-wf-sgml06"
    >sgml06.xml:6:15: Expecting a Name</test>
  <test id="not-wf-sgml07"
    >sgml07.xml:3:20: Invalid content model: expecting '(', 'EMPTY' or 'ANY'</test>
  <test id="not-wf-sgml08"
    >sgml08.xml:3:20: Invalid content model: expecting '(', 'EMPTY' or 'ANY'</test>
  <test id="not-wf-sgml09"
    >sgml09.xml:4:41: Expecting end of ELEMENT definition</test>
  <test id="not-wf-sgml10"
    >sgml10.xml:3:66: Expecting end of ELEMENT definition</test>
  <test id="not-wf-sgml11"
    >sgml11.xml:3:20: Invalid content model: expecting '(', 'EMPTY' or 'ANY'</test>
  <test id="not-wf-sgml12"
    >sgml12.xml:3:20: Invalid content model: expecting '(', 'EMPTY' or 'ANY'</test>
  <test id="not-wf-sgml13"
    >sgml13.xml:3:23: Expecting operator in content model</test>
  <test id="not-wf-sa-001"
    >001.xml:3:1: Invalid name: '?'</test>
  <test id="not-wf-sa-002"
    >002.xml:2:2: Invalid name: '.doc'</test>
  <test id="not-wf-sa-003"
    >003.xml:1:8: Processing Instruction must specify a target name</test>
  <test id="not-wf-sa-004"
    >004.xml:1:6: Processing instruction must end with '?>'</test>
  <test id="not-wf-sa-005"
    >005.xml:1:6: Processing instruction must end with '?>'</test>
  <test id="not-wf-sa-008"
    >008.xml:1:6: Invalid entity name</test>
  <test id="not-wf-sa-006"
    >006.xml:1:21: '--' cannot appear in comments</test>
  <test id="not-wf-sa-007"
    >007.xml:1:6: Entity references must end with ';'.
Did you want to use &amp;amp;?</test>
  <test id="not-wf-sa-009"
    >009.xml:1:8: Invalid character in character reference: R</test>
  <test id="not-wf-sa-010"
    >010.xml:1:8: Invalid entity name</test>
  <test id="not-wf-sa-011"
    >011.xml:1:8: Attributes must have an explicit value</test>
  <test id="not-wf-sa-012"
    >012.xml:1:9: Attribute values must be quoted</test>
  <test id="not-wf-sa-013"
    >013.xml:1:14: '&lt;' not authorized in attribute values. Possible end of value at 013.xml:1:12</test>
  <test id="not-wf-sa-014"
    >014.xml:1:10: '&lt;' not authorized in attribute values</test>
  <test id="not-wf-sa-015"
    >015.xml:1:9: Attribute values must be quoted</test>
  <test id="not-wf-sa-016"
    >016.xml:1:14: Expecting a Name</test>
  <test id="not-wf-sa-017"
    >017.xml:1:6: CDATA sections must end with ']]&gt;'</test>
  <test id="not-wf-sa-018"
    >018.xml:1:6: CDATA must be followed immediately by '['</test>
  <test id="not-wf-sa-019"
    >019.xml:1:8: Expecting a Name</test>
  <test id="not-wf-sa-020"
    >020.xml:1:12: Invalid entity name</test>
  <test id="not-wf-sa-022"
    >022.xml:1:15: Invalid character in character reference: :</test>
  <test id="not-wf-sa-023"
    >023.xml:1:6: Invalid name: '12'</test>
  <test id="not-wf-sa-024"
    >024.xml:2:2: Invalid name: '123'</test>
  <test id="not-wf-sa-025"
    >025.xml:1:6: Text may not contain the litteral ']]&gt;'</test>
  <test id="not-wf-sa-026"
    >026.xml:1:7: Text may not contain the litteral ']]&gt;'</test>
  <test id="not-wf-sa-027"
    >027.xml:2:1: Comments must end with '-->'</test>
  <test id="not-wf-sa-028"
    >028.xml:2:1: Processing instruction must end with '?>'</test>
  <test id="not-wf-sa-029"
    >029.xml:1:10: Text may not contain the litteral ']]&gt;'</test>
  <test id="not-wf-sa-030"
    >030.xml:1:19: Invalid character code: 12</test>
  <test id="not-wf-sa-031"
    >031.xml:1:24: Invalid character code: 12</test>
  <test id="not-wf-sa-032"
    >032.xml:1:24: Invalid character code: 12</test>
  <test id="not-wf-sa-033"
    >033.xml:1:9: Invalid character code: 27</test>
  <test id="not-wf-sa-034"
    >034.xml:1:5: Invalid character code: 12</test>
  <test id="not-wf-sa-035"
    >035.xml:1:9: Expecting a Name</test>
  <test id="not-wf-sa-036"
    >036.xml:2:1: Non-white space found at top level</test>
  <test id="not-wf-sa-037"
    >037.xml:2:1: Character references cannot appear at top-level</test>
  <test id="not-wf-sa-038"
    >038.xml:1:22: Attributes may appear only once: x</test>
  <test id="not-wf-sa-039"
    >039.xml:1:9: Name differ for closing tag (expecting a, opened line 1)</test>
  <test id="not-wf-sa-040"
    >040.xml:2:1: Too many children for top-level node, when adding &lt;doc&gt;</test>
  <test id="not-wf-sa-041"
    >041.xml:2:1: Too many children for top-level node, when adding &lt;doc&gt;</test>
  <test id="not-wf-sa-042"
    >042.xml:1:12: Tags must end with a '&gt;' symbol</test>
  <test id="not-wf-sa-043"
    >043.xml:2:1: Non-white space found at top level</test>
  <test id="not-wf-sa-044"
    >044.xml:1:7: Too many children for top-level node, when adding &lt;doc&gt;</test>
  <test id="not-wf-sa-045"
    >045.xml:2:3: Expecting a space</test>
  <test id="not-wf-sa-046"
    >046.xml:2:3: Expecting a space</test>
  <test id="not-wf-sa-047"
    >047.xml:2:4: Invalid name: '/'</test>
  <test id="not-wf-sa-048"
    >048.xml:3:1: Non-white space found at top level</test>
  <test id="not-wf-sa-049"
    >049.xml:3:13: Name differ for closing tag (expecting doc, opened line 1)</test>
  <test id="not-wf-sa-050"
    >050.xml:1:0: No root element specified</test>
  <test id="not-wf-sa-051"
    >051.xml:2:1: Non-white space found at top level</test>
  <test id="not-wf-sa-052"
    >052.xml:2:1: Character references cannot appear at top-level</test>
  <test id="not-wf-sa-053"
    >053.xml:1:6: Name differ for closing tag (expecting doc, opened line 1)</test>
  <test id="not-wf-sa-054"
    >054.xml:2:38: Expecting SystemID after PUBLIC</test>
  <test id="not-wf-sa-055"
    >055.xml:2:1: Element not allowed in the DTD</test>
  <test id="not-wf-sa-056"
    >056.xml:1:17: Expecting end of DTD</test>
  <test id="not-wf-sa-057"
    >057.xml:2:25: Expecting end of ENTITY definition</test>
  <test id="not-wf-sa-058"
    >058.xml:3:22: Invalid character ',' in ATTLIST enumeration</test>
  <test id="not-wf-sa-059"
    >059.xml:3:28: Invalid default value for attribute</test>
  <test id="not-wf-sa-060"
    >060.xml:3:19: Invalid type for attribute</test>
  <test id="not-wf-sa-061"
    >061.xml:2:29: Require whitespace between public and system IDs</test>
  <test id="not-wf-sa-062"
    >062.xml:2:13: Expecting a space</test>
  <test id="not-wf-sa-063"
    >063.xml:2:1: INCLUDE and IGNORE sections only allowed in the external DTD subset</test>
  <test id="not-wf-sa-064"
    >064.xml:3:21: Expecting a space</test>
  <test id="not-wf-sa-065"
    >065.xml:3:17: Expecting a space</test>
  <test id="not-wf-sa-066"
    >066.xml:3:27: Expecting a space</test>
  <test id="not-wf-sa-067"
    >067.xml:3:23: Expecting a space</test>
  <test id="not-wf-sa-068"
    >068.xml:3:26: Space is required between NOTATION keyword and list of enumerated</test>
  <test id="not-wf-sa-069"
    >069.xml:4:30: Expecting space before NDATA declaration</test>
  <test id="not-wf-sa-070"
    >070.xml:1:41: '--' cannot appear in comments</test>
  <test id="not-wf-sa-071"
    >entity e3:1:1: Entity cannot reference itself</test>
  <test id="not-wf-sa-072"
    >072.xml:1:6: Undefined entity 'foo'</test>
  <test id="not-wf-sa-073"
    >073.xml:4:6: Undefined entity 'f'</test>
  <test id="not-wf-sa-075"
    >entity e3:1:1: Entity cannot reference itself</test>
  <test id="not-wf-sa-076"
    >076.xml:1:9: Undefined entity 'foo'</test>
  <test id="not-wf-sa-077"
    >entity foo:1:1: Undefined entity 'bar'</test>
  <test id="not-wf-sa-078"
    >078.xml:3:24: Undefined entity 'foo'</test>
  <test id="not-wf-sa-079"
    >entity e3:1:1: Entity cannot reference itself</test>
  <test id="not-wf-sa-080"
    >entity e3:1:1: Entity cannot reference itself</test>
  <test id="not-wf-sa-081"
    >081.xml:4:9: Attribute values cannot reference external entities</test>
  <test id="not-wf-sa-082"
    >082.xml:4:24: Attribute values cannot reference external entities</test>
  <test id="not-wf-sa-088"
    >088.xml:6:13: '&lt;' not authorized in attribute values</test>
  <test id="not-wf-sa-089"
    >089.xml:2:33: NDATA annotation not allowed for parameter entities</test>
  <test id="not-wf-sa-090"
    >entity e:1:9: '&lt;' not authorized in attribute values</test>
  <test id="not-wf-sa-091"
    >091.xml:3:33: NDATA annotation not allowed for parameter entities</test>
  <test id="not-wf-sa-092"
    >entity e:1:9: Invalid entity name</test>
  <test id="not-wf-sa-093"
    >093.xml:1:8: Invalid character in character reference: X</test>
  <test id="not-wf-sa-094"
    >094.xml:1:7: 'version' must be the first argument to &lt;?xml?&gt;</test>
  <test id="not-wf-sa-095"
    >095.xml:1:7: 'version' must be the first argument to &lt;?xml?&gt;</test>
  <test id="not-wf-sa-096"
    >096.xml:1:20: values must be separated by spaces</test>
  <test id="not-wf-sa-097"
    >097.xml:1:16: Illegal version number in &lt;?xml?&gt; processing instruction</test>